services:
  aerostack2:
    image: aerostack2_sherec_navigation:latest
    build:
      context: ./docker/
      args:
        AS2_BRANCH: main
      dockerfile: Dockerfile
    container_name: as2_sherec_nav
    environment:
      - DISPLAY=$DISPLAY
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=0  # Asegúrate de que coincida con tu red
    privileged: true
    volumes:
      # X11 para ver simulador/RViz
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # PROYECTO ACTUAL
      - .:/root/sherec_nav/
      # TU CÓDIGO DE AEROSTACK2
      # ~/as2_main:/root/aerostack2_ws
      - ~/aerostack2_ws:/root/aerostack2_ws
    network_mode: "host"
    stdin_open: true
    tty: true
    command: tail -f /dev/null
