services:
  aerostack2:
    image: aerostack2_sherec_navigation:latest
    build:
      context: ./docker/
      args:
        AS2_BRANCH: main
      dockerfile: Dockerfile
    container_name: as2_sherec_nav
    environment:
      DISPLAY: $DISPLAY
      ROS_LOCALHOST_ONLY: 1
    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Proyecto
      - .:/root/sherec_nav/
      # Aerostack2 compilado con el loop reactivo
      - ~/aerostack2_ws:/root/aerostack2_ws
    stdin_open: true
    tty: true
    network_mode: "host"
    command: tail -f /dev/null
